spring:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/oauth?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    initialization-mode: always

  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: 1234

  redis:
    host: localhost
    port: 6379
    database: 11

service:
  name: oauth-server-local

logging:
  slack:
    webhook-uri: https://hooks.slack.com/services/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
    channel: oauth-local
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework : debug