service:
  name: oauth-server

logging:
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS"


server:
  port: 80
  servlet:
    context-path: /oauth

rsa:
  password: issacIsHandsome
  privateKey: privateKey.jks
  alias: privateKey